theme = "catppuccin_macchiato"

[editor]
cursorline = true
cursorcolumn = true
line-number = "absolute"
mouse = false
bufferline = "always"
color-modes = true
end-of-line-diagnostics = "hint"

[editor.whitespace.render]
tab = "all"
# newline = "all"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name", "read-only-indicator"]
right = ["diagnostics", "position", "file-encoding", "file-type"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-progress-messages = true
display-inlay-hints = true

[editor.inline-diagnostics]
#cursor-line = "info"
#other-lines = "info"

[keys.normal]
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"

H = "goto_first_nonwhitespace"
L = "goto_line_end"

space.B = ":echo %sh{git blame -L %{cursor_line},+1 %{buffer_name}}"
