colors:
  primary:
    background: "#282A36" # Dracula vim theme color
    foreground: "#D8DEE9"

  normal:
    black: "#3B4252"
    red: "#BF616A"
    green: "#A3BE8C"
    yellow: "#EBCB8B"
    blue: "#81A1C1"
    magenta: "#B48EAD"
    cyan: "#56B6C2"
    # cyan: "#88C0D0"
    white: "#ABB2BF"

  bright:
    black: "#5C6370"
    red: "#E06C75"
    green: "#98C379"
    yellow: "#D19A66"
    blue: "#51AFEF"
    magenta: "#C678DD"
    cyan: "#56B6C2"
    white: "#ECEFF4"

font:
  normal:
    family: "Hack Nerd Font Mono"
    style: Regular

  bold:
    family: "Hack Nerd Font Mono"
    style: Bold

  italic:
    family: "Hack Nerd Font Mono"
    style: Italic

  bold_italic:
    family: "Hack Nerd Font Mono"
    style: Bold Italic

  size: 12.0

window:
  opacity: 0.9
  padding:
    x: 2
    y: 2
  glyph_offset:
    x: 2
    y: 2

scrolling:
  history: 10000
  multiplier: 10

draw_bold_text_with_bright_colors: true

live_config_reload: true
