#!/bin/sh

# Non-river stuff
swaybg -i ~/Pictures/wallpapers/wallpaper.png --mode fill &
swayidle -w & 
waybar &
kanshi &
fnott &

dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river
systemctl --user stop pipewire wireplumber xdg-desktop-portal xdg-desktop-portal-wlr
systemctl --user start wireplumber xdg-desktop-portal-wlr

# River settings
# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
# Set background and border color
riverctl background-color       0x002B36
riverctl border-color-focused   0xFE8019
riverctl border-color-unfocused 0x00000000
riverctl border-width           3

# Input settings
riverctl set-repeat 35 175
riverctl input      pointer-1739-52823-SYNA8009:00_06CB:CE57_Touchpad tap enabled

# Make certain views start floating
riverctl float-filter-add app-id float
riverctl float-filter-add title  "popup title with spaces"

riverctl focus-follows-cursor normal
riverctl set-cursor-warp      on-output-change

# New windows attach at the bottom of the stack
riverctl attach-mode bottom

riverctl default-layout toelayout

# Spawns
riverctl map normal Super+Shift   Return spawn kitty
riverctl map normal Super         R      spawn fuzzel.sh
riverctl map normal Super+Shift   O      spawn swaylock
riverctl map normal Super+Shift   S      spawn "screenshot-wayland.sh region-copy"

for mode in normal locked
do
    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pactl set-sink-volume @DEFAULT_SINK@ +5%'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pactl set-sink-volume @DEFAULT_SINK@ -5%'
    riverctl map $mode None XF86AudioMute         spawn 'pactl set-sink-mute @DEFAULT_SINK@ toggle'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with light (https://github.com/haikarainen/light)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'light -A 5'
    riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 5'
done

# River control
riverctl map normal      Super       W      close
riverctl map normal      Super+Shift E      exit
riverctl map normal      Super       Space  toggle-float
riverctl map normal      Super       F      toggle-fullscreen
riverctl map normal      Super       F11    enter-mode passthrough
riverctl map passthrough Super       F11    enter-mode normal

# Window and output selection
riverctl map normal Super Return         zoom
riverctl map normal Super H focus-output left
riverctl map normal Super J focus-view   previous
riverctl map normal Super K focus-view   next
riverctl map normal Super L focus-output right

# Move windows between outputs
riverctl map normal Super+Shift H spawn "riverctl send-to-output left && riverctl focus-output left"
riverctl map normal Super+Shift L spawn "riverctl send-to-output right && riverctl focus-output right"

# Rivertile commands
riverctl map normal Super       Comma  send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super       Period send-layout-cmd rivertile "main-ratio +0.05"

riverctl map normal Super+Shift I      send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift D      send-layout-cmd rivertile "main-count -1"

riverctl map normal Super       Up     send-layout-cmd rivertile "main-location top"
riverctl map normal Super       Right  send-layout-cmd rivertile "main-location right"
riverctl map normal Super       Down   send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super       Left   send-layout-cmd rivertile "main-location left"

# Mouse mapping
riverctl map-pointer normal Super BTN_LEFT  move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Tagging
for i in $(seq 1 5)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super       0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags    $all_tags

#rivertile -view-padding 2 -outer-padding 2
python3 ${HOME}/.config/river/toelayout.py -i 2 -o 2
