# Basic options
initial_screen = "queue"
use_nerdfont = true
notify = true
gapless = true
default_keybindings = false
volnorm = true

[keybindings]
"Enter" = "play"
" " = "playpause"

"o" = "open selected"
"O" = "back"

"+" = "volup 1"
"-" = "voldown 1"

"a" = "queue"
"d" = "delete"

"b" = "seek -5000"
"f" = "seek +5000"
"B" = "seek -60000"
"F" = "seek +60000"

"n" = "next"
"p" = "previous"

"r" = "repeat"
"R" = "shuffle"

"D" = "delete"
"S" = "save"

"1" = "focus queue"
"2" = "focus library"
"3" = "focus search"

"h" = "move left 1"
"j" = "move down 1"
"k" = "move up 1"
"l" = "move right 1"

"q" = "quit"

[notification_format]
title = "NCSpot"
body = "%artists - %title (%duration)"

# Catppuccin-macchiato
[theme]
background = "default"
primary = "#cad3f5"
secondary = "light black"
title = "#a6da95"
playing = "#a6da95"
playing_bg = "#363a4f"
playing_selected = "#c6a0f6"
highlight = "#c6a0f6"
highlight_bg = "#363a4f"
error = "#cad3f5"
error_bg = "#ed8796"
statusbar = "#f5a97f"
statusbar_progress = "#f5a97f"
statusbar_bg = "default"
cmdline = "#cad3f5"
cmdline_bg = "#363a4f"
